//CREAR UN PROGRAMA EN C QUE MUESTRE UN MENÚ CON LAS OPCIONES SUMAR, RESTAR, 
//MULTIPLICAR  Y  DIVIDIR,  EL  PROGRAMA  SOLICITARÁ  UNA  OPCIÓN  Y  REALIZARÁ  LA  TAREA 
//ELEGIDA,  SE  DEBE  USAR  UNA  FUNCIÓN  PARA  MOSTRAR  EL  MENÚ,  PEDIR  LOS  DATOS  EN  EL 
//MAIN Y DESPUÉS USAR FUNCIONES PARA REALIZAR LOS CÁLCULOS.  